name: Build Windows EXE for 8BallPool

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download JavaFX SDK
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_windows-x64_bin-sdk.zip -OutFile javafx-sdk.zip
          Expand-Archive javafx-sdk.zip -DestinationPath .
          Rename-Item -Path .\javafx-sdk-21.0.1 -NewName javafx

      - name: Build JAR
        run: .\gradlew clean build -x test

      - name: Create custom JavaFX runtime
        run: |
          jlink `
            --module-path "$env:JAVA_HOME\jmods;javafx\lib" `
            --add-modules java.base,java.desktop,javafx.controls,javafx.fxml `
            --output custom-runtime

      - name: Package with jpackage
        run: |
          jpackage `
            --type exe `
            --input build\libs `
            --name 8BallPool `
            --main-jar 8BallPoolGradle-1.0-SNAPSHOT.jar `
            --main-class Main `
            --runtime-image custom-runtime `
            --dest dist

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: 8BallPool
          path: dist/8BallPool/8BallPool.exe