name: Build Windows EXE for 8BallPool

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build JAR
        run: .\gradlew clean build -x test

      - name: Package with jpackage
        run: |
          jpackage `
            --type exe `
            --input build\libs `
            --name 8BallPool `
            --main-jar 8BallPoolGradle-1.0-SNAPSHOT.jar `
            --main-class Main `
            --runtime-image custom-runtime `
            --dest dist

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: 8BallPool
          path: dist/8BallPool-1.0.exe

      - name: Show jpackage output
        run: Get-ChildItem -Recurse dist

      - name: Run built EXE (optional)
        run: |
          .\dist\8BallPool-1.0.exe